<nav class="navbar fixed-top navbar-expand-md navbar-">
<a class="navbar-brand" href="index.php">
<img class="navBarLogo" src="img/federLogo.png" alt="Logo"> </a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
<ul class="navbar-nav mr-auto">
<li class="nav-item">
<a class="nav-link" href="index.php">Home
<span class="sr-only">(current)</span>
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="webdev.php">WebDev</a>
</li>
<li class="nav-item">
<a class="nav-link" href="ux-ui.php">UX/UI</a>
</li>
<li class="nav-item">
<a class="nav-link" href="devilize.php">Devilize</a>
</li>
<li class="nav-item">
<a class="nav-link" href="audio.php">Audio</a>
</li>
<li class="nav-item">
<a class="nav-link" href="contact.php">Contacto</a>
</li>
</ul>
</div>
</nav>